### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by ssuess**
Here are the changes I made to your plugin:

- finished UUID token work
- added some things to the admin for revoking tokens
- added a new regen endpoint for automatic extension of tokens
- added a little code for oauth co-existence (you may want to remove this)
- cleaned up the Readme a little
- added a little to the plugin about (feel free to change this as you wish, I don't care if I get any credit)
- made base validity one month (you may want to remove this too)

Feel free to ask any questions. hope this is helpful. Thanks for the great work you have already done.

### CODE REVIEW

**Comment by ssuess** [comment]
Hi @Tmeister 

I just made the following further changes:

- new revoke endpoint (logout)
- all tokens will be invalidated if user changes his password.

Hope you find it useful. Thanks.

**Comment by ssuess** [comment]
Any news on merging these changes? Or any changes you need to this request? (this is the first one I have done, so I may have made a mistake, let me know if that is the case). Thanks!

**Comment by ssuess** [comment]
@Tmeister ??

**Comment by luizbills** [comment]
up

**Review by sviluppomania — APPROVED** [review]

**Pull request closed without merging**
