### PR TITLE
Add filter for JWT issuer (iss).

### PR DESCRIPTION
**Pull request by ghost**
This to be able to be able to be authenticated on multiple blogs in a multisite.

### CODE REVIEW

**Comment by mcorkum** [comment]
+1 for this

**Comment by mieradi** [comment]
+1. Need this

**Comment by troychaplin** [comment]
I wish this was already merged in... Please add this @Tmeister

**Comment by marceloglacial** [comment]
+1 REALLY need this!

**Review by sviluppomania — APPROVED** [review]

**Pull request closed without merging**
